spring:
  application:
    name: consumer
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://ybiao.qicp.vip:40884/eureka/,http://ikanp.top:7001/eureka/,http://121.37.188.7:7001/eureka/
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 5000