server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.191.78:3307/test?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 476900
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.bosssoft.model
logging:
  level:
    root: debug