server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.93.191.78:3306/mybatis?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    data-password: 476900

