server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.191.78:3306/customerMS?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 476900
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 47.93.191.78
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 476900**
    #jedis:
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 300
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
logging:
  level:
    root: info