server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://ybiao.qicp.vip:40884/eureka/,http://ikanp.top:7001/eureka/,http://121.36.111.199:7001/eureka/
    register-with-eureka: false
spring:
  application:
    name: ribbon-consumer