server:
  port: 80
spring:
  application:
    name: client-feign
logging:
  level:
    root: info
eureka:
  instance:
    instance-id: client-feign
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka,http://eureka2.com:7002/eureka
feign:
  hystrix:
    enabled: true